In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
b=np.array([2,4,6])
a_dot_b=np.dot(a,b)
print(a_dot_b)

28


In [5]:
a=np.array([2,3])
b=np.array([4,4])
a_cross_b=np.cross(a,b)
print(a_cross_b)

-4


In [7]:
random_matrix=np.random.rand(3,3)
print(random_matrix)

[[0.81082098 0.70892277 0.39585478]
 [0.98308775 0.13063364 0.94077556]
 [0.4635141  0.58860888 0.03842516]]


In [9]:
random_int=np.random.randint(100,size=(3,3))
print(random_int)

[[39 13 29]
 [63 66 67]
 [80 59  2]]


In [10]:
random_int1=np.random.randint(200,size=(4,4))
print(random_int1)

[[ 77 155  61 134]
 [ 83 153   9 154]
 [176 123 140  66]
 [ 77 170  64  88]]


In [16]:
#matrix with all the values 1
matrix_3=np.ones((2,3),dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


In [18]:
#null matrix or zero matrix
null_matrix=np.zeros((3,3),dtype=int)
print(null_matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [23]:
#identity matrix
identity_matrix=np.identity(3,dtype=int)
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [24]:
#transpose of the matrix
a=np.random.randint(100,size=(3,3))
print(a)

[[96  1  2]
 [ 6  3 86]
 [12 12 57]]


In [25]:
transpose_of_a=np.transpose(a)
print(transpose_of_a)

[[96  6 12]
 [ 1  3 12]
 [ 2 86 57]]


In [26]:
b=np.random.randint(200,size=(3,3))
transpose_of_b=np.transpose(b)
print(transpose_of_b)


[[ 49 173 115]
 [120 141  75]
 [ 82  21 185]]


In [27]:
#matrix Addition'
a=np.array([[2,3],[4,6]])
b=np.array([[2,5],[8,9]])
print(a)
print(b)

[[2 3]
 [4 6]]
[[2 5]
 [8 9]]


In [28]:
sum=a+b
print(sum)

[[ 4  8]
 [12 15]]


In [34]:
#multiply a matrix by a  scaler
a=5
b=np.random.randint(100,size=(3,3))
print(b)
product=np.multiply(a,b)
print(product)

[[87 51 55]
 [10 36 54]
 [44 38 49]]
[[435 255 275]
 [ 50 180 270]
 [220 190 245]]
